In [2]:
import pandas as pd

In [5]:
pd.read_csv('client.csv')

,Unnamed: 0,Name,Email,Mobile,Skills,Designation,Experience_Period,education,countries,regions,cities,Resume_path
0,0,RAMASWAMY RAJESH,rajeshramaswamy@yahoo.com,+91 8807022101,['Skills and Competences\n\n07/2010—till date\...,"['cfo', 'business partner', 'partner', 'scorek...",36.0,"['Education, Achievements and Certificates\nCr...","['Bahrain', 'Malaysia', 'India', 'United Kingd...",[],"['Bangalore', 'Chennai', 'Commerce', 'Banks', ...",/home/anush/Desktop/flask_name/new_pdf/2014.docx
1,1,Language Proficiency,lingeswaran.k@yahoo.com,0507477548,"[['english', 'photoshop', 'tamil', 'microsoft'...",['autocad'],0.0,['Education\t B.E:\nMechanical Engineering K.S...,[],[],['Contact'],/home/anush/Desktop/flask_name/new_pdf/659.docx
2,2,VITAE Khulood,khulood.alsaad@gmail.com,(+973) 3960 8896,['Skills \n\n \n \n \n \n \n \n \n \n \n \n \n...,"['vice president', 'president', 'implementatio...",30.0,['EDUCATION AND '],"['Bahrain', 'Kingdom of Bahrain']",[],[],/home/anush/Desktop/flask_name/new_pdf/2706.pdf
3,3,KEVIN R. CHOKSEY,kwins936@gmail.com,(+91) 9099852552,"[['government', 'table tennis', 'quiz', 'publi...","['associate', 'assistant professor', 'patient ...",1.0,['EDUCATION AND TRAINING IN PREVIOUS MEDICAL \...,['India'],"['Maharashtra', 'Istanbul', 'Goa']","['Mumbai', 'Indore', 'Vadodara', 'Rajkot', 'Ah...",/home/anush/Desktop/flask_name/new_pdf/3053.pdf
4,4,MD ABU MUZAFFAR,abu.muzaffar20@gmail.com,+919262676759,"[['known : English', ' Hindi', ' Urdu', 'Hobbi...",['project engineer'],0.0,['Educational '],[],[],"['Bangalore', 'Chennai', 'May', 'Tata', 'Mar',...",/home/anush/Desktop/flask_name/new_pdf/1547.docx
...,...,...,...,...,...,...,...,...,...,...,...,...
5385,5385,EMAIL ADDRESS,tabarak198400@gmail.com,0091996863,"[['birth', 'hindi', 'arabic', 'passport', 'eng...",[],9.0,['EDUCATIONAL QULIFICATION : 10TH...,[],[],[],/home/anush/Desktop/flask_name/new_pdf/1564.docx
5386,5386,DEEPAK PRAJAPATI,dkp7102@gmail.com,9720865949,['Skills and Strength\n\n\uf0b7 Motivating and...,[],0.0,['Nan'],[],[],['Vista'],/home/anush/Desktop/flask_name/new_pdf/172.pdf
5387,5387,NaN,E-Mail:vikaspujari89@gmail.com|,0844771925,['Skills '],"['business development', 'it sales executive',...",4.0,['Nan'],['INDIA'],[],"['Ghaziabad', 'English']",/home/anush/Desktop/flask_name/new_pdf/417.docx
5388,5388,NASEER AHMED,naseerahmedkhan7@gmail.com,+918688272671,['Skills •Attention to Detail •Deadline-Orient...,"['account representative', 'representative', '...",3.0,['Education & Credential \n\n\nCertification \...,['India'],[],"['Commerce', 'Bank', 'Industry', 'English']",/home/anush/Desktop/flask_name/new_pdf/1662.docx
5389,5389,NaN,NaN,NaN,[[]],[],0.0,['Nan'],[],[],['Grand'],/home/anush/Desktop/flask_name/new_pdf/2978.pdf

In [8]:
pd.read_csv('client2.csv')

,Name,Email,Mobile,Skills,Designation,Experience_Period,education,new_skill,countries,regions,cities,Resume_path
0,RAMASWAMY RAJESH,rajeshramaswamy@yahoo.com,+91 8807022101,"['english', 'ifrs', 'layout', 'revenue', 'inve...","['cfo', 'business partner', 'partner', 'scorek...",36.0,"['Education, Achievements and Certificates\nCr...",['Skills and Competences\n\n07/2010—till date\...,"['Qatar', 'Malaysia', 'Bahrain', 'United Kingd...",[],"['Bangalore', 'Chennai', 'Doha']",/home/anush/Downloads/resume_pdf_doc_dataset/c...
1,Language Proficiency,lingeswaran.k@yahoo.com,0507477548,"['english', 'technology', 'pro', 'xp', 'design...",['autocad'],0.0,['Education\t B.E:\nMechanical Engineering K.S...,"[['english', 'technology', 'pro', 'xp', 'desig...",[],[],[],/home/anush/Downloads/resume_pdf_doc_dataset/c...
2,CURRICULUM VITAE,abu.muzaffar20@gmail.com,+919262676759,"['known : English', ' Hindi', ' Urdu', 'Hobbie...",['project engineer'],0.0,['Educational '],"[['known : English', ' Hindi', ' Urdu', 'Hobbi...",[],[],"['Bangalore', 'Chennai']",/home/anush/Downloads/resume_pdf_doc_dataset/c...
3,CURRICULUM VITAE,shubh.bhatt007@gmail.com,8564892556,"[':', ')', 'B.tech 2011-15 Babu Banarasi Das U...",['summer internship'],7.0,['Nan'],"[[':', ')', 'B.tech 2011-15 Babu Banarasi Das ...",[],[],[],/home/anush/Downloads/resume_pdf_doc_dataset/c...
4,SHOIEB ALI,shoiebali368@gmail.com,+917017789274,"[':', '· Customer service skill', '· Retantion...","['team leader', 'sales person', 'operator']",7.0,['Nan'],['Skills :\n\nCustomer service skill\nRetantio...,[],[],[],/home/anush/Downloads/resume_pdf_doc_dataset/c...
...,...,...,...,...,...,...,...,...,...,...,...,...
5395,MUYALA EDWARD,muyalaeddy@gmail.com,+254719240410,"['2011 Malava Boys High School', 'Kakamega', '...",['legal intern'],1.0,['Education\n\n'],['Skills\n\uf0b7 Bankruptcy Expert\n\uf0b7\n\u...,['Kenya'],['Kisumu'],[],/home/anush/Downloads/resume_pdf_doc_dataset/c...
5396,CURRICULUM VITAE,sulthan.thameem@gmail.com,091 8428,"['Known - English', ' Hindi', ' Malayalam', ' ...","['operator', 'plant technician', 'technician',...",25.0,['Education:\n\nTertiary\n1989 -1992 The New C...,"[['Known - English', ' Hindi', ' Malayalam', '...","['Kingdom of Saudi Arabia', 'Saudi Arabia', 'I...",[],['Chennai'],/home/anush/Downloads/resume_pdf_doc_dataset/c...
5397,House No.1248,azims0975@gmail.com,9717885303,"['.', 'Basic Knowledge of Computer.', 'Auto Ca...",[],0.0,['EDUCATIONAL '],['SKILLS.\n\n\uf0b7 Basic Knowledge of Compute...,[],[],[],/home/anush/Downloads/resume_pdf_doc_dataset/c...
5398,CURRICULUM VITAE,dkp7102@gmail.com,9720865949,"['and Strength', 'Motivating and goal oriented...",[],0.0,['Nan'],['Skills and Strength\n\n\uf0b7 Motivating and...,[],[],[],/home/anush/Downloads/resume_pdf_doc_dataset/c...
5399,NaN,NaN,NaN,[],[],0.0,['Nan'],[[]],[],[],[],/home/anush/Downloads/resume_pdf_doc_dataset/c...

In [9]:
pd.read_csv('client22.csv')

,Unnamed: 0,Name,Email,Mobile,Skills,Designation,Experience_Period,education,countries,regions,cities,Resume_path
0,0,DREW MENDEZ,DREW.MENDEZ@AOL.COM,(646)633-2926,['SKILLS : \n\nSoftware: Microsoft; Powerpoint...,"['student', 'customer service manager', 'servi...",NaN,"['EDUCATION : \n\nLAGUARDIA COMMUNITY COLLEGE,...",[],['Reading'],"['Reading', 'Ridgewood', 'Long Island City', '...",/home/anush/Desktop/flask_name/Training_resume...
1,1,Carol James,jennifercj57@hotmail.com,NaN,"[['organization', 'strong leader ship', 'Good ...","['ward clerk', 'scheduling coordinator', 'qual...",5.0,['Nan'],[],[],[],/home/anush/Desktop/flask_name/Training_resume...
2,2,NaN,Analeciam22@gmail.com,954-404-3789,"[['reviews', 'customer satisfaction', 'reliabi...","['customer service representative', 'service r...",0.0,['Nan'],[],[],"['Fort Lauderdale', 'Moore']",/home/anush/Desktop/flask_name/Training_resume...
3,3,Sara Lopez,Email-slopez7571@yahoo.com,561-354-8002,"[['history', 'go', 'desserts', 'salads', 'writ...","['service manager', 'radiologic technician', '...",0.0,['Education\n\n•Graduate 2015- Fort Pierce Cen...,[],[],"['Indian River', 'Frank']",/home/anush/Desktop/flask_name/Training_resume...
4,4,Alice Brown,jaisnana11@GMAIL.COM,(239)672-5433,['Skills\xa0\n\nCustomer Service\xa0\n\n'],[],2.0,['Education\xa0\n\nMONTH 10-2010\xa0\xa0\n\nS...,[],['Florida'],"['Melbourne', 'Florida']",/home/anush/Desktop/flask_name/Training_resume...
5,5,Yajaira Mercedes,tequiero1@msn.com,(401) 440-9858,"[['customer retention', 'reviews', 'dynamics',...","['office administration', 'office support', 'q...",9.0,"[""Education and Training \n\n03/2015 - 07/201...",[],[],"['Taunton', 'West Haven', 'Providence', 'Johns...",/home/anush/Desktop/flask_name/Training_resume...
6,6,_GoBack]Ashley,A_goupee90@outlook.com,772-418-3579,"[['Type 50-80 wpm', 'Advanced in Microsoft off...","['supervisor', 'administration assistant', 'fr...",5.0,['Nan'],[],[],[],/home/anush/Desktop/flask_name/Training_resume...
7,7,Christine Colangelo,christineleecolangelo@gmail.com,(772) 444.5944,['SKILLS\xa0\n\n● Types 80+ WPM\xa0\n● Receive...,"['office manager', 'long term', 'owner', 'ware...",10.0,"['EDUCATION\xa0\n\nPSLHS, Port Saint Lucie \n\...",[],[],"['Port Saint Lucie', 'Christine']",/home/anush/Desktop/flask_name/Training_resume...
8,8,_GoBack][image,JOEY.P.PAYNE@GMAIL.COM,772-563-8721,['Skills \t\n'],"['administrative professional', 'office manage...",14.0,['Education and Training \t\nHyles - Anders...,[],[],"['Ocala', 'Payne', 'Place']",/home/anush/Desktop/flask_name/Training_resume...
9,9,CAROLINA NARBUTAS,carolinanarbutas@gmail.com,973-862-9739,"['SKILLS \n\n• Reliable, punctual and honest ...","['office manager', 'property manager', 'real e...",0.0,['EDUCATION \n\nDECEMBER 2015 \nREAL ESTATE AG...,['MEXICO'],['Florida'],"['Mexico', 'Stuart', 'Carolina', 'Florida', 'R...",/home/anush/Desktop/flask_name/Training_resume...
10,10,NaN,Idalisbraddy@hotmail.com,772-336-8212,"[['r', 'f', 'o', 'store', 'holidays', 'player'...","['full time', 'part time', 'store manager', 'p...",0.0,['Nan'],[],[],"['Golden', 'Jensen Beach', 'Johnston', 'Contact']",/home/anush/Desktop/flask_name/Training_resume...
11,11,Christine Thermilus,livingnparadise@comcast.net,772 618 0992,"[['interpersonal skills', 'autism', 'operation...",['front desk'],12.0,['Education:\n\nLa Salle High School ...,[],[],"['Miami', 'Port Saint Lucie', 'Davie', 'Christ...",/home/anush/Desktop/flask_name/Training_resume...
12,12,Lleyni Perez,Perezln29@gmail.com,772-380-6956,"['Skills: 40 wpm, Microsoft Word, Microsoft E...","['administrative assistant', 'production assis...",12.0,['Education: South Fork High School \n\nS...,[],[],"['Palm City', 'Spanish', 'English']",/home/anush/Desktop/flask_name/Training_resume...
13,13,NaN,NaN,772-200-9799,"[['operations', 'research', 'administrative', ...","['part time', 'administrative assistant', 'off...",0.0,['EDUCATION: \nSt James Academy High School \...,[],[],"['Sales', 'Part']",/home/anush/Desktop/flask_name/Training_resume...
14,14,CHRISTINE M,cnelson430@gmail.com,(772) 979-6868,"[['interpersonal skills', 'administrative', 'o...","['administrative assistant', 'office manager']",11.0,['Nan'],[],['Nelson'],"['Nelson', 'Palm City', 'Port Saint Lucie', 'S...",/home/anush/Desktop/flask_name/Training_resume...
15,15,PAMELA RANDHAN,pamelamarie76@yahoo.com,(772) 501-9795,['SKILLS \n\n• Proficient in Microsoft Office...,"['assistant manager', 'store manager', 'part t...",23.0,['EDUCATION \n\n • Fort Pierce Cent...,[],['Florida'],"['Okeechobee', 'Winter Haven', 'Florida', 'Out...",/home/anush/Desktop/flask_name/Training_resume...
16,16,Christine Thermilus,livingnparadise@comcast.net,772 618 0992,"[['interpersonal skills', 'autism', 'operation...",['front desk'],12.0,['Education:\n\nLa Salle High School ...,[],[],"['Miami', 'Port Saint Lucie', 'Davie', 'Christ...",/home/anush/Desktop/flask_name/Training_resume...
17,17,​Lisa Wilson,LW82734@gmail.com,NaN,['Skills\nMedical\xa0Terminology\xa0\xa0\xa0\x...,"['customer service representative', 'service r...",15.0,"['EDUCATION\n\nMarch,\xa02008\n\nJanuary,\xa02...",[],['Florida'],"['Stuart', 'Florida']",/home/anush/Desktop/flask_name/Training_resume...
18,18,Natalie Demello,NatD91@Gmail.com,(772)985-5758,"[['Friendly', 'Organized']]","['personal assistant', 'group leader']",0.0,['Nan'],[],[],[],/home/anush/Desktop/flask_name/Training_resume...
19,19,Kasandra Abbott,klei80sbaby@gmail.com,7725012977,"[""Skills\n\nExcel (2 years), Microsoft Office ...","['administrative assistant', 'office assistant...",8.0,['Education\n\nHigh School Diploma\nHome schoo...,[],[],"['Melbourne', 'Vero Beach', 'Sebastian', 'Outl...",/home/anush/Desktop/flask_name/Training_resume...
20,20,Aracelis Claudio,aclaudiodiaz@gmail.com,561-529-0370,['Skills \nRecruitment\nResponsible for prepar...,"['administrative assistant', 'front desk', 'fr...",0.0,['Education\t\t\t\t\nBronx Community College \...,[],[],"['Bronx', 'Strong']",/home/anush/Desktop/flask_name/Training_resume...
21,21,Carol M. Cobb,carolmcobb@gmail.com,512-673-3033,"[""Skills\nMarketing Strategies\n\nOrganization...","['facilitator', 'change management', 'real est...",0.0,"[""Educational Consultant\nPeople's Publishing\...",[],[],"['Aurora', 'Port Saint Lucie', 'Deming']",/home/anush/Desktop/flask_name/Training_resume...
22,22,Shaina T. Karpinski,stkarpinski4@yahoo.com,772-267-3639,"[['microsoft publisher', 'property management'...","['surgery scheduler', 'secretary']",13.0,['Education: Graduated from Port Saint Lucie H...,[],[],[],/home/anush/Desktop/flask_name/Training_resume...
23,23,Shawn Findlater,Shawnbaghem@gmail.com,985-3577,"['Skills, and a Fast Learner.\nReference \nTas...","['management associate', 'associate', 'supervi...",5.0,['EDUCATION\nIndian River State College\n2013 ...,[],[],"['Liberty', 'Sandwich', 'Martin', 'Part']",/home/anush/Desktop/flask_name/Training_resume...
24,24,Yahoo Mail,(jenniferoneil3985@gmail.com),342-2106,"[['staff scheduling', 'phones', 'inventory con...","['department manager', 'portrait consultant', ...",20.0,['Nan'],[],[],"['March', 'West Palm Beach', 'Palm City', 'Stu...",/home/anush/Desktop/flask_name/Training_resume...
25,25,Sandi Barlow,sandibarlow628@yahoo.com,732-267-4972,"[['& Abilities', 'Supervise inside/outside per...",['project coordinator'],0.0,['Nan'],[],['Wakefield'],['Wakefield'],/home/anush/Desktop/flask_name/Training_resume...
26,26,Elizabeth Cuty,Ecuty4840@gmail.com,772-475-4840,"['Skills & Abilities \n\nQuickBooks Pro, Windo...","['office manager', 'president', 'notary public']",15.0,['Education \n\nHIGH SCHOOL DIPLOMA '],[],[],"['Elizabeth', 'Outlook']",/home/anush/Desktop/flask_name/Training_resume...
27,27,Kassandra Diaz,kassy.diaz93@gmail.com,7722379678,"['Skills\n\ninventory management, telxon use, ...","['pharmacy technician', 'technician', 'sales a...",11.0,['Education\n\nPharmacy\n\n\xa0\n\xa0\n\x0cWal...,[],[],"['Homestead', 'Us']",/home/anush/Desktop/flask_name/Training_resume...
28,28,Valentina Sanders,navielisvillegas@gmail.com,786-552-2735,['Skills and abilities\n\n ...,"['certified public accountant', 'public accoun...",15.0,['Education University of Carabobo. 200...,[],"['Florida', 'Carabobo']","['Orlando', 'Spanish', 'Florida', 'Bank', 'San...",/home/anush/Desktop/flask_name/Training_resume...
29,29,West Palm,Mrs.Laboy@outlook.com,5612811317,['SkillsFaxing documentsScheduling and calenda...,"['administrative assistant', 'accountant', 'ac...",0.0,['Education and TrainingHigh School DiplomaPal...,[],[],"['West Palm Beach', 'Spanish', 'Sales', 'Engli...",/home/anush/Desktop/flask_name/Training_resume...
30,30,William Feis,xspy2000@live.com,772-925-1274,"[['sports', 'case', 'wash', 'synthesis', 'gene...","['service inspector', 'inspector', 'collector'...",36.0,"['EDUCATION:\nSouthern Career, Boca Raton, Flo...",[],"['Florida', 'New Jersey']","['Boca Raton', 'Vero Beach', 'Belmar', 'Bayvil...",/home/anush/Desktop/flask_name/Training_resume...
31,31,OVERVIEW SERVICE,NaN,585 2018,"[['store', 'hiring practices', 'milestones', '...","['founder', 'founder and ceo', 'ceo', 'operati...",0.0,['Nan'],[],['Florida'],"['March', 'Florida', 'Jones', 'Don', 'Monster'...",/home/anush/Desktop/flask_name/Training_resume...
32,32,Daniel Nyhuis,dannyhuis@yahoo.com,772-353-7748,['Skills acquired: knowledge and use of the De...,"['customer service advocate', 'food service', ...",9.0,['EDUCATION\n\nSouth Fork High School\n\n10000...,['United States'],['Florida'],"['Apt', 'March', 'Jupiter', 'Stuart', 'Jensen ...",/home/anush/Desktop/flask_name/Training_resume...
33,33,Jessica Domineck,Jessicadomineck13@gmail.com,954-200-5437,"[['administrative', 'store', 'd', 'office', 'o...","['supervisor', 'store manager', 'appointment s...",7.0,"['EDUCATION\nAtlantic Technical College, Ft. L...",[],[],"['Lauderdale', 'North Miami']",/home/anush/Desktop/flask_name/Training_resume...
34,34,Donna DiRoma,Darkstar1dd@gmail.com,718-775-2563,['Skills \n\nCustomer Relations \nComputer...,"['customer service agent', 'service agent', 'a...",35.0,['Education \n\nMt. Vernon High School Mt. V...,[],[],['Donna'],/home/anush/Desktop/flask_name/Training_resume...
35,35,Teresa Fogarty,teresa92178@gmail.com​,(772) 834-3245,['Skills Summary: \n'],"['collections specialist', 'regional director'...",24.0,['Education\n\nMolloy College\nCertified Medic...,[],[],"['March', 'Fort Myers', 'Key West', 'Vero Beac...",/home/anush/Desktop/flask_name/Training_resume...

In [10]:
pd.read_csv('Mannual_Resume40 (6).csv')

,Name,Email,Mobile,Skills,Experience Period,Experience,Education,Location,Country,Region,City,Specialist/Certification,Interest
0,Jessica Domineck,Jessicadomineck13@gmail.com,954-200-5437,"Proficient in MS Office 2010,Proficient in Wi...",7.0,"HR Supervisor - DIGITAL ARTS ENTERPRISES, Nor...",Excel Security licensed D and G,Pompano Beach Fl,NaN,NaN,NaN,NaN,NaN
1,CHRISTINE M NELSON,cnelson430@gmail.com,772-979-6868,"Proficient in QuickBooks, Proficient in Micro...",1.0,Administrative Assistant / Office Manager,NaN,"Ave Port Saint Lucie, FL 34983",NaN,NaN,NaN,NaN,NaN
2,Analecia Moore \n,Analeciam22@gmail.com,954-404-3789,NaN,7.0,Customer Service Representative - Alorica: Fo...,NaN,Fort Lauderdale,NaN,NaN,NaN,NaN,NaN
3,Ashley Goupee,A_goupee90@outlook.com,772-418-3579,"Advanced in Microsoft office tools (Excel, Wor...",5.0,ADMINISTRATION ASSISTANT - ZENITH FINANCIAL N...,"BACHELOR’S IN BUSINESS MANAGEMENT, ADMINSTRATI...","SE Laika LN Port Saint Lucie,",NaN,NaN,NaN,NaN,NaN
4,Ashley O’Toole,NaN,NaN,"Experienced in - Word, Excel, Outlook, PowerPo...",1.0,Kitchen and Service Manager,NaN,"island Circle, Port St Lucie, FL \n",NaN,NaN,NaN,NaN,NaN
5,Brandi Ann Shady,NaN,772-200-9799,"Microsoft Word,Microsoft Excel,Microsoft Powe...",NaN,Legal/Administrative Assistant\n\n Insurance ...,High School - Diploma,SW Heather St Port St. Lucie,NaN,NaN,NaN,NaN,NaN
6,CAROL JAMES,jennifercj57@hotmail.com,772-528-3735,NaN,23.0,Customer Care Corrdinator -Senior Home Care S...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,CAROLINA NARBUTAS,carolinanarbutas@gmail.com,973-862-9739,"Microsoft Office,Quickbooks",5.0,"OFFICE MANAGER, AMERICAN KITCHEN AND FLOORING...",Real Estate Agent License\n\n,NaN,NaN,NaN,NaN,NaN,NaN
8,CECILIA MORALES,NaN,772-924-6412,"MS Windows ,Criminal law,Estates Wills & Trus...",NaN,"INSURANCE AGENT, FIORELLA INSURANCE AGENCY\n\...","BACHELOR’S IN LEGAL STUDIES, KEISER UNIVERSIT...",SW Curry St Port Saint Lucie Florida,NaN,NaN,NaN,NaN,NaN
9,Christine Colangelo,christineleecolangelo@gmail.com\n,772-444.5944,"Types 80 WPM,,Microsoft- Word, Excel, Office,...",4.0,"Office Manager - TriCounty, Fort Pierce\n\n O...","High School Diploma - PSLHS, Port Saint Lucie\n",NaN,NaN,NaN,NaN,NaN,NaN
10,Daniel Nyhuis,dannyhuis@yahoo.com,772-353-7748,"Proficient with computers and POS systems,Typ...",9.0,Customer Service Advocate - Express Scripts I...,South Fork High School\n\n Indian River State...,"SE Palm Beach Road, United States\n",NaN,NaN,NaN,NaN,NaN
11,Shaina T. Karpinski,stkarpinski4@yahoo.com,772-267-3639,"Mds, lytec Availity, Microsoft Word, Excel an...",6.0,Urology Speacilists Of Stuart\n\n Receptionis...,Graduated - Port Saint Lucie High School,SE Volkerts Terrace Port Saint Lucie,NaN,NaN,NaN,NaN,NaN
12,DREW MENDEZ,DREW.MENDEZ@AOL.COM,646-633-2926,Microsoft; Powerpoint Outlook; Excel; Microso...,6.0,"Teacher - ST LUCIE PUBLIC SCHOOLS, PORT ST LU...",Associates Degree In Criminal Justice - LAGUA...,NW TREASURE COAST DR. JENSEN BEACH FL,NaN,NaN,NaN,NaN,NaN
13,Elizabeth Cuty,Ecuty4840@gmail.com,772-475-4840,"QuickBooks Pro, Windows, Microsoft Office, Exc...",3.0,"OFFICE MANAGER - JRL SAFE CLEAN, LLC\n\n RECE...",HIGH SCHOOL DIPLOMA - SAINT JAMES ACADEMY,SW Jeremko Avenue Port Saint Lucie,NaN,NaN,NaN,NaN,NaN
14,Aracelis Claudio Diaz,aclaudiodiaz@gmail.com,561-529-0370,"Microsoft: Word, PowerPoint, & Outlook,Make e...",10.0,Office Manager - Solomon Trucking Inc \n\n Pr...,Major: AS Paralegal Studies\n\n Medical Billi...,SW Ruffner Ct Port St Lucie FL,NaN,NaN,NaN,NaN,NaN
15,Idalis Braddy,NaN,NaN,NaN,3.0,Cashier \n\n Patient Coordinator\n\n Theater ...,High school Diploma\n\n Business Computer Sof...,NaN,NaN,NaN,NaN,NaN,NaN
16,Jack Little,jlittle69273@gmail.com,561-312-9075,"Windows (XP thru 10) ,Windows Server ,Microso...",26.0,"Production Control - Twin Vee Powercats, Fort...",NaN,Vero Beach,NaN,NaN,NaN,NaN,NaN
17,Joey Payne,JOEY.P.PAYNE@GMAIL.COM,772-563-8721,"Office Management,,Database Administration ,H...",14.0,Office Manager/Executive Assistant - Gospel ...,"Bachelor of Science in Pastoral Theology, Youth",Ocala,NaN,NaN,NaN,NaN,NaN
18,Kasandra Abbott,\nklei80sbaby@gmail.com,7725012977,"Microsoft Office,Microsoft Outlook",8.0,Office Manager/Medical Receptionist\n\n Child...,High School Diploma,NaN,NaN,NaN,NaN,NaN,NaN
19,Kassandra Diaz\n,kassy.diaz93@gmail.com,7722379678,NaN,3.0,Pharmacy Technician\n\n Cashier\n\n Sales Ass...,NaN,Port Saint Lucie\n,NaN,NaN,NaN,NaN,NaN
20,Lisa Wilson,LW82734@gmail.com,(77 301­2751,"Microsoft Office,Filing/Editing,\nMicrosoft Wi...",NaN,"Jetson TV & Appliance Centers, Accounts Payab...","ACADEMY OF PRACTICAL NURSING\nWEST PALM BEACH,...","SW Aguero St \nPort Saint Lucie, Florida 3495",NaN,NaN,NaN,NaN,NaN
21,Lleyni Perez,Perezln29@gmail.com,772-380-6956,"40 wpm, Microsoft Word, Microsoft Excel, and AMI",6.0,"Indian River Shutter Company Palm City, FL Pro...",Graduated,NaN,NaN,NaN,NaN,NaN,NaN
22,PAMELA RANDHAN,pamelamarie76@yahoo.com,(77 501-9795,"Proficient in Microsoft Office Suite (Word, Ex...",17.0,Assistant Manager (August 2018 - Present)\nNo...,NaN,"3048 SE 37th Avenue\n, Okeechobee, Florida 34974",NaN,NaN,NaN,NaN,TO235 – Limited Surety Agent – Florida Bail Bo...
23,Alice Brown,jaisnana11@GMAIL.COM,(239)672-5433,Customer Service,8.0,Customer Service Rep.\n,Diploma,"202 Petals Road\nFort Pierce,Floridaa",NaN,NaN,NaN,NaN,NaN
24,Donna DiRoma,Darkstar1dd@gmail.com,718-775-2563,NaN,NaN,Customer Service Agent 2008-2014,Graduated,NaN,NaN,NaN,NaN,NaN,NaN
25,BETSY LABOY,Mrs.Laboy@outlook.com,5612811317,NaN,NaN,NaN,High School Diploma,5985 Orange Rd West Palm Beach FL 33413,NaN,NaN,NaN,NaN,NaN
26,Carol M. Cobb,carolmcobb@gmail.com,512-673-3033,NaN,NaN,NaN,NaN,"234 Brazilian Circle\nPort Saint Lucie, FL 349...",NaN,NaN,NaN,NaN,NaN
27,Sandi Barlow,sandibarlow628@yahoo.com,732-267-4972,"Supervise inside/outside personnel, accounts r...",29.0,Office Staff\n5/18-7/18\nProject Coordinator\n...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Valentina Sanders,navielisvillegas@gmail.com,786-552-2735,"Certified Public Accountant,Proficient and flu...",13.0,Administrative Assistant - Bookkeper\n JMC S...,Certified Public Accountant,"2117 S.E. Dolphin Rd.\n Port St Lucie, Florida...",NaN,NaN,NaN,NaN,NaN
29,Kelly Murnane,Murnane.kelly@gmail.com,772-344-7246,"Rental Assistant,Government Administration/Sup...",22.0,P/T Rental Assistant November 2013 – May 2016...,07866 Diploma,"270 SW Panther Trace Port Saint Lucie, FL 34953",NaN,NaN,NaN,NaN,NaN
30,NATALIE DEMELLO,NatD91@Gmail.com,(77985-5758,"Friendly,Organize,Experience with house keepin...",NaN,PERSONAL ASSISTANT -NOV 2009 – DEC 2016\nYOUT...,PSYCHOLOGY,NaN,NaN,NaN,NaN,NaN,NaN
31,Christine Thermilus,livingnparadise@comcast.net,772 618 0992,Great communication skills (verbal & written) ...,9.0,Volunteer/ Assisted teachers with classroom ac...,State College,NaN,NaN,NaN,NaN,NaN,NaN
32,Jennifer O'Neil,jennifer3985@yahoo.com,(77-342-2106\n,NaN,18.0,Department manager - November 2013-March 2019\...,High School Diploma,NaN,NaN,NaN,NaN,NaN,NaN
33,Daniel Nyhuis,dannyhuis@yahoo.com,772-353-7748,"Customer service experience, including face-to...",8.0,"in upscale restaurant environment, requiring p...",State College,"[706 S 8th St, Fort Pierce FL 34950",NaN,NaN,NaN,NaN,NaN
34,Sara Lopez,slopez7571@yahoo.com\n,772-692-0465\n,NaN,NaN,NaN,State College,"533 NW Cornell Ave Port Saint Lucie FL, 34983",NaN,NaN,NaN,NaN,NaN
35,Shawn Findlater,Shawnbaghem@gmail.com,(77-985-3577,"Excellent written, typing, and communication s...",12.0,Two years of Mental Health Service experience\...,State College,"2338 SW Savage Blvd, Port St Lucie, FL, 34953",NaN,NaN,NaN,NaN,NaN
36,Teresa Fogarty,teresa92178@gmail.com,(77 834-3245\n,Experienced customer service and collections s...,16.0,Lead A/R-August 2017 to present\nFront Desk Re...,Certified Medical Biller/Coder,"3055 62\nnd Court, Vero Beach, FL 32966\n",NaN,NaN,NaN,NaN,NaN
37,William Feis,xspy2000@live.com,772-925-1274,NaN,31.0,"January 2018 – Present Howl Alert, INC.\nEmplo...",NaN,"39 Woodland Drive, #106\nVero Beach, Florida 3...",NaN,NaN,NaN,NaN,NaN
38,Yajaira Mercedes,tequiero1@msn.com,(40 440-9858,"Microsoft Word, Excel, Spreadsheet, Introducti...",9.0,Couriers and Messengers Manager-03/2015 - 07/2...,Associate's Degree(Business Administration),"2057 SE Glen Ridge Drive Port Saint Lucie, FL ...",NaN,NaN,NaN,NaN,NaN

In [11]:
pd.read_csv('naukari.csv')

,Uniq Id,Crawl Timestamp,Job Title,Job Salary,Job Experience Required,Key Skills,Role Category,Location,Functional Area,Industry,Role
0,9be62c49a0b7ebe982a4af1edaa7bc5f,2019-07-05 01:46:07 +0000,Digital Media Planner,Not Disclosed by Recruiter,5 - 10 yrs,Media Planning| Digital Media,Advertising,Mumbai,"Marketing , Advertising , MR , PR , Media Plan...","Advertising, PR, MR, Event Management",Media Planning Executive/Manager
1,3c52d436e39f596b22519da2612f6a56,2019-07-06 08:04:50 +0000,Online Bidding Executive,Not Disclosed by Recruiter,2 - 5 yrs,pre sales| closing| software knowledge| clien...,Retail Sales,"Pune,Pune","Sales , Retail , Business Development","IT-Software, Software Services",Sales Executive/Officer
2,ffad8a2396c60be2bf6d0e2ff47c58d4,2019-08-05 15:50:44 +0000,Trainee Research/ Research Executive- Hi- Tec...,Not Disclosed by Recruiter,0 - 1 yrs,Computer science| Fabrication| Quality check|...,R&D,Gurgaon,"Engineering Design , R&D","Recruitment, Staffing",R&D Executive
3,7b921f51b5c2fb862b4a5f7a54c37f75,2019-08-05 15:31:56 +0000,Technical Support,"2,00,000 - 4,00,000 PA.",0 - 5 yrs,Technical Support,Admin/Maintenance/Security/Datawarehousing,Mumbai,"IT Software - Application Programming , Mainte...","IT-Software, Software Services",Technical Support Engineer
4,2d8b7d44e138a54d5dc841163138de50,2019-07-05 02:48:29 +0000,Software Test Engineer -hyderabad,Not Disclosed by Recruiter,2 - 5 yrs,manual testing| test engineering| test cases|...,Programming & Design,Hyderabad,IT Software - QA & Testing,"IT-Software, Software Services",Testing Engineer
...,...,...,...,...,...,...,...,...,...,...,...
29995,3510f2146b514f112eaa9706a16b3900,2019-07-06 21:12:51 +0000,MTS-Software-Engineer,Not Disclosed by Recruiter,9 - 12 yrs,Graphics| C++| USB| Project management| SOC| ...,Programming & Design,Bengaluru,"IT Software - Embedded , EDA , VLSI , ASIC , C...","Semiconductors, Electronics",Software Developer
29996,4af8c56f5b4c535b1974065003f2d548,2019-08-05 23:55:08 +0000,Client Relationship Manager,Not Disclosed by Recruiter,1 - 5 yrs,Service delivery| LMS| CRE| Integration servi...,Operations,Chennai,"ITES , BPO , KPO , LPO , Customer Service , Op...","Education, Teaching, Training",Operations Manager
29997,43d5b806b26ed99d3ebfc8f366b4cdd1,2019-08-05 09:41:29 +0000,Assoc. Prof.- CS,Not Disclosed by Recruiter,4 - 6 yrs,Counselor| Mentor| Trainer| Advisor| Teaching,University Level,Howrah,"Teaching , Education , Training , Counselling","Education, Teaching, Training",Lecturer/Professor
29998,8bc87d14cf56564f16b6d4bae80180be,2019-08-06 01:44:55 +0000,Application/Cyber Security Specialist-Pune,Not Disclosed by Recruiter,5 - 10 yrs,Security Analysis| Software Development Life ...,Programming & Design,Pune,"IT Software - Application Programming , Mainte...","IT-Software, Software Services",Software Developer
29999,9c7045d111814a6f39fe461eab2b0bf8,2019-07-06 22:24:55 +0000,Press Release Writer - SEO,Not Disclosed by Recruiter,2 - 7 yrs,Press release| Public relations| Publishing| ...,Online/Digital Marketing,Bengaluru,"Marketing , Advertising , MR , PR , Media Plan...","IT-Software, Software Services",Search Engine Optimisation /SEO Specialist

In [12]:
pd.read_csv('resume_extration_2_5000.csv')

,Name,Email,Mobile,Skills,Designation,Experience_Period,education,countries,regions,cities
0,RAMASWAMY RAJESH,rajeshramaswamy@yahoo.com,+91 8807022101,"['accounts receivable', 'reporting systems', '...","['cfo', 'business partner', 'partner', 'scorek...",36.0,"['Education, Achievements and Certificates\nCr...","['Qatar', 'India', 'Malaysia', 'United Kingdom...",[],"['Bangalore', 'Chennai', 'Doha']"
1,Language Proficiency,lingeswaran.k@yahoo.com,0507477548,"['english', 'project work', 'xp', 'microsoft o...",['autocad'],0.0,['Education\t B.E:\nMechanical Engineering K.S...,[],[],[]
2,CURRICULUM VITAE,abu.muzaffar20@gmail.com,+919262676759,"['known : English', ' Hindi', ' Urdu', 'Hobbie...",['project engineer'],0.0,['Educational '],[],[],"['Bangalore', 'Chennai']"
3,CURRICULUM VITAE,shubh.bhatt007@gmail.com,8564892556,"[':', ')', 'B.tech 2011-15 Babu Banarasi Das U...",['summer internship'],7.0,['Nan'],[],[],[]
4,SHOIEB ALI,shoiebali368@gmail.com,+917017789274,"[':', '· Customer service skill', '· Retantion...","['team leader', 'sales person', 'operator']",7.0,['Nan'],[],[],[]
...,...,...,...,...,...,...,...,...,...,...
5395,MUYALA EDWARD,muyalaeddy@gmail.com,+254719240410,"['2011 Malava Boys High School', 'Kakamega', '...",['legal intern'],1.0,['Education\n\n'],['Kenya'],['Kisumu'],[]
5396,CURRICULUM VITAE,sulthan.thameem@gmail.com,091 8428,"['Known - English', ' Hindi', ' Malayalam', ' ...","['operator', 'plant technician', 'technician',...",25.0,['Education:\n\nTertiary\n1989 -1992 The New C...,"['Saudi Arabia', 'QATAR', 'India', 'Kingdom of...",[],['Chennai']
5397,House No.1248,azims0975@gmail.com,9717885303,"['.', 'Basic Knowledge of Computer.', 'Auto Ca...",[],0.0,['EDUCATIONAL '],[],[],[]
5398,CURRICULUM VITAE,dkp7102@gmail.com,9720865949,"['and Strength', 'Motivating and goal oriented...",[],0.0,['Nan'],[],[],[]
5399,NaN,NaN,NaN,[],[],0.0,['Nan'],[],[],[]